version: '3.8'

services:
  tic-tac-toe:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: tic-tac-toe-game


networks:
  default:
    name: tic-tac-toe-network